<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<title>OMNeT++ Simulation Library: cException Class Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<!-- Generated by Doxygen 1.6.3 -->
<div class="navigation" id="top">
  <div class="tabs">
    <ul>
      <li><a href="main.html"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.html"><span>Related&nbsp;Pages</span></a></li>
      <li><a href="modules.html"><span>Modules</span></a></li>
      <li class="current"><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
      <li><a href="dirs.html"><span>Directories</span></a></li>
    </ul>
  </div>
  <div class="tabs">
    <ul>
      <li><a href="annotated.html"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.html"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.html"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="contents">
<h1>cException Class Reference<br/>
<small>
[<a class="el" href="group__SimSupport.html">Utility classes</a>]</small>
</h1><!-- doxytag: class="cException" -->
<p>Exception class.  
<a href="#_details">More...</a></p>

<p><code>#include &lt;<a class="el" href="cexception_8h_source.html">cexception.h</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for cException:</div>
<div class="dynsection">
 <div class="center">
  <img src="classcException.png" usemap="#cException_map" alt=""/>
  <map id="cException_map" name="cException_map">
<area href="classcDeleteModuleException.html" alt="cDeleteModuleException" shape="rect" coords="0,56,152,80"/>
<area href="classcRuntimeError.html" alt="cRuntimeError" shape="rect" coords="162,56,314,80"/>
<area href="classcStackCleanupException.html" alt="cStackCleanupException" shape="rect" coords="324,56,476,80"/>
<area href="classcTerminationException.html" alt="cTerminationException" shape="rect" coords="486,56,638,80"/>
</map>
 </div>
</div>

<p><a href="classcException-members.html">List of all members.</a></p>
<table border="0" cellpadding="0" cellspacing="0">
<tr><td colspan="2"><h2>Public Member Functions</h2></td></tr>
<tr><td colspan="2"><div class="groupHeader">Constructors, destructor</div></td></tr>
<tr><td colspan="2"><div class="groupText"><p><a class="anchor" id="amgrpd3ad4460ef59f0ea3709ab506a5ef1ce"></a> </p>
</div></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#ae37c072e7711457f2baadd31e0dc99b2">cException</a> (OppErrorCode errcode,...)</td></tr>
<tr><td class="memItemLeft" align="right" valign="top">&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#a7f7fcd4d98b0c32fb9b85030a90f3c54">cException</a> (const char *msg,...)</td></tr>
<tr><td class="memItemLeft" align="right" valign="top">&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#a49e99763b394cd114aef2dc543958472">cException</a> (const <a class="el" href="classcObject.html">cObject</a> *where, OppErrorCode errcode,...)</td></tr>
<tr><td class="memItemLeft" align="right" valign="top">&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#a9661042c3ba62741d8afde2238719fbf">cException</a> (const <a class="el" href="classcObject.html">cObject</a> *where, const char *msg,...)</td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a20bdf9ba513c144630d8b809e95fda1c"></a><!-- doxytag: member="cException::cException" ref="a20bdf9ba513c144630d8b809e95fda1c" args="(const cException &amp;)" -->
&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#a20bdf9ba513c144630d8b809e95fda1c">cException</a> (const <a class="el" href="classcException.html">cException</a> &amp;)</td></tr>
<tr><td class="memItemLeft" align="right" valign="top">virtual <a class="el" href="classcException.html">cException</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#a7aae9b928c595645f2918a897eb14c2b">dup</a> () const </td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a616a152a7a238d75cd1f93ece2e0ce15"></a><!-- doxytag: member="cException::~cException" ref="a616a152a7a238d75cd1f93ece2e0ce15" args="()" -->
virtual&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#a616a152a7a238d75cd1f93ece2e0ce15">~cException</a> ()  throw ()</td></tr>
<tr><td colspan="2"><div class="groupHeader">Updating the exception message</div></td></tr>
<tr><td colspan="2"><div class="groupText"><p><a class="anchor" id="amgrp589108395547a120a3cbe17459b3fcab"></a> </p>
</div></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="afad7de0aaeadf1be7aac3174ce67a73f"></a><!-- doxytag: member="cException::setMessage" ref="afad7de0aaeadf1be7aac3174ce67a73f" args="(const char *txt)" -->
virtual void&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#afad7de0aaeadf1be7aac3174ce67a73f">setMessage</a> (const char *txt)</td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a668b1549d73a30b9ff3f2d4e615c3de0"></a><!-- doxytag: member="cException::prependMessage" ref="a668b1549d73a30b9ff3f2d4e615c3de0" args="(const char *txt)" -->
virtual void&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#a668b1549d73a30b9ff3f2d4e615c3de0">prependMessage</a> (const char *txt)</td></tr>
<tr><td colspan="2"><div class="groupHeader">Getting exception info</div></td></tr>
<tr><td colspan="2"><div class="groupText"><p><a class="anchor" id="amgrpbbc01e0724fe2e48b34944667e5f1de9"></a> </p>
</div></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">virtual bool&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#ae94e8963aaae31fc8609986128d38d52">isError</a> () const </td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a66e376301220fd82c9da9bdeab664365"></a><!-- doxytag: member="cException::getErrorCode" ref="a66e376301220fd82c9da9bdeab664365" args="() const " -->
virtual int&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#a66e376301220fd82c9da9bdeab664365">getErrorCode</a> () const </td></tr>
<tr><td class="memItemLeft" align="right" valign="top">virtual const char *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#aec27fc122c18bc5432fb798188bb0af7">what</a> () const   throw ()</td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6d6e6a3f46967732ed62cc19a2805169"></a><!-- doxytag: member="cException::getFormattedMessage" ref="a6d6e6a3f46967732ed62cc19a2805169" args="() const " -->
virtual std::string&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#a6d6e6a3f46967732ed62cc19a2805169">getFormattedMessage</a> () const </td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a14bc3aa629707ee37a10d724b8fa451f"></a><!-- doxytag: member="cException::getSimulationStage" ref="a14bc3aa629707ee37a10d724b8fa451f" args="() const " -->
virtual int&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#a14bc3aa629707ee37a10d724b8fa451f">getSimulationStage</a> () const </td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa6a0dcd4d786e12318ef826867087353"></a><!-- doxytag: member="cException::getEventNumber" ref="aa6a0dcd4d786e12318ef826867087353" args="() const " -->
virtual eventnumber_t&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#aa6a0dcd4d786e12318ef826867087353">getEventNumber</a> () const </td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af4d9f0a1904d84fb89d8a20977a974af"></a><!-- doxytag: member="cException::getSimtime" ref="af4d9f0a1904d84fb89d8a20977a974af" args="() const " -->
virtual simtime_t&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#af4d9f0a1904d84fb89d8a20977a974af">getSimtime</a> () const </td></tr>
<tr><td class="memItemLeft" align="right" valign="top">virtual bool&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#a5222f000f4d39b905ce471cf8ee4ded0">hasContext</a> () const </td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae05fe03bbe292c5c2907e08da8f62e30"></a><!-- doxytag: member="cException::getContextClassName" ref="ae05fe03bbe292c5c2907e08da8f62e30" args="() const " -->
virtual const char *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#ae05fe03bbe292c5c2907e08da8f62e30">getContextClassName</a> () const </td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a42d56ca373f6025d0517cc081523b769"></a><!-- doxytag: member="cException::getContextFullPath" ref="a42d56ca373f6025d0517cc081523b769" args="() const " -->
virtual const char *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#a42d56ca373f6025d0517cc081523b769">getContextFullPath</a> () const </td></tr>
<tr><td class="memItemLeft" align="right" valign="top">virtual int&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#a65b5c33d50a8a76db2eba3b6868821a3">getModuleID</a> () const </td></tr>
<tr><td colspan="2"><h2>Protected Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">void&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#a3dc884d1fd5a29cbb7ef2c0fa7851717">init</a> (const <a class="el" href="classcObject.html">cObject</a> *obj, OppErrorCode errorcode, const char *fmt, va_list va)</td></tr>
</table>
<hr/><a name="_details"></a><h2>Detailed Description</h2>
<p>Exception class. </p>
<hr/><h2>Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="ae37c072e7711457f2baadd31e0dc99b2"></a><!-- doxytag: member="cException::cException" ref="ae37c072e7711457f2baadd31e0dc99b2" args="(OppErrorCode errcode,...)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">cException::cException </td>
          <td>(</td>
          <td class="paramtype">OppErrorCode&nbsp;</td>
          <td class="paramname"> <em>errcode</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&nbsp;</td>
          <td class="paramname"> <em>...</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Error is identified by an error code, and the message comes from a string table. </p>
<p>The error string may expect printf-like arguments (s, d) which also have to be passed to the constructor. </p>

</div>
</div>
<a class="anchor" id="a7f7fcd4d98b0c32fb9b85030a90f3c54"></a><!-- doxytag: member="cException::cException" ref="a7f7fcd4d98b0c32fb9b85030a90f3c54" args="(const char *msg,...)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">cException::cException </td>
          <td>(</td>
          <td class="paramtype">const char *&nbsp;</td>
          <td class="paramname"> <em>msg</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&nbsp;</td>
          <td class="paramname"> <em>...</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>To be called like printf(). </p>
<p>The error code is set to eCUSTOM. </p>

</div>
</div>
<a class="anchor" id="a49e99763b394cd114aef2dc543958472"></a><!-- doxytag: member="cException::cException" ref="a49e99763b394cd114aef2dc543958472" args="(const cObject *where, OppErrorCode errcode,...)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">cException::cException </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classcObject.html">cObject</a> *&nbsp;</td>
          <td class="paramname"> <em>where</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">OppErrorCode&nbsp;</td>
          <td class="paramname"> <em>errcode</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&nbsp;</td>
          <td class="paramname"> <em>...</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Error is identified by an error code, and the message comes from a string table. </p>
<p>The error string may expect printf-like arguments (s, d) which also have to be passed to the constructor. The 1st arg is the object where the error occurred: its class and object name will be prepended to the message like this: "(cArray)arr". </p>

</div>
</div>
<a class="anchor" id="a9661042c3ba62741d8afde2238719fbf"></a><!-- doxytag: member="cException::cException" ref="a9661042c3ba62741d8afde2238719fbf" args="(const cObject *where, const char *msg,...)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">cException::cException </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classcObject.html">cObject</a> *&nbsp;</td>
          <td class="paramname"> <em>where</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const char *&nbsp;</td>
          <td class="paramname"> <em>msg</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&nbsp;</td>
          <td class="paramname"> <em>...</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>To be called like printf(). </p>
<p>The error code is set to eCUSTOM. The 1st arg is the object where the error occurred: its class and object name will be prepended to the message like this: "(cArray)arr". </p>

</div>
</div>
<hr/><h2>Member Function Documentation</h2>
<a class="anchor" id="a7aae9b928c595645f2918a897eb14c2b"></a><!-- doxytag: member="cException::dup" ref="a7aae9b928c595645f2918a897eb14c2b" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual <a class="el" href="classcException.html">cException</a>* cException::dup </td>
          <td>(</td>
          <td class="paramname"></td>
          <td>&nbsp;)&nbsp;</td>
          <td> const<code> [inline, virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Virtual copy constructor. </p>
<p>We unfortunately need to copy exception objects when handing them back from an activity(). </p>

<p>Reimplemented in <a class="el" href="classcTerminationException.html#a3cc34be98273933d33c17328b9c0f5e6">cTerminationException</a>, <a class="el" href="classcRuntimeError.html#a6d34e0bf66e83e7c209bb72df3b816f8">cRuntimeError</a>, <a class="el" href="classcDeleteModuleException.html#a66df169476c0f09ae5a66bd3616c6143">cDeleteModuleException</a>, and <a class="el" href="classcStackCleanupException.html#a6106d0f66dee0d823e1f6f4868c9ea65">cStackCleanupException</a>.</p>

</div>
</div>
<a class="anchor" id="a65b5c33d50a8a76db2eba3b6868821a3"></a><!-- doxytag: member="cException::getModuleID" ref="a65b5c33d50a8a76db2eba3b6868821a3" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual int cException::getModuleID </td>
          <td>(</td>
          <td class="paramname"></td>
          <td>&nbsp;)&nbsp;</td>
          <td> const<code> [inline, virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Returns the ID of the module where the exception occurred, or -1 if it was not inside a module. </p>
<p>The module may not exist any more when the exception is caught (ie. if the exception occurs during network setup, the network is cleaned up immediately). </p>

</div>
</div>
<a class="anchor" id="a5222f000f4d39b905ce471cf8ee4ded0"></a><!-- doxytag: member="cException::hasContext" ref="a5222f000f4d39b905ce471cf8ee4ded0" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual bool cException::hasContext </td>
          <td>(</td>
          <td class="paramname"></td>
          <td>&nbsp;)&nbsp;</td>
          <td> const<code> [inline, virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Returns true if the exception has "context info", that is, it occurred within a known module or channel. </p>
<p><a class="el" href="classcException.html#ae05fe03bbe292c5c2907e08da8f62e30" title="Returns the class name (NED type name) of the context where the exception occurred...">getContextClassName()</a>, <a class="el" href="classcException.html#a42d56ca373f6025d0517cc081523b769" title="Returns the full path of the context where the exception occurred.">getContextFullPath()</a> and <a class="el" href="classcException.html#a65b5c33d50a8a76db2eba3b6868821a3" title="Returns the ID of the module where the exception occurred, or -1 if it was not inside...">getModuleID()</a> may only be called if this method returns true. </p>

</div>
</div>
<a class="anchor" id="a3dc884d1fd5a29cbb7ef2c0fa7851717"></a><!-- doxytag: member="cException::init" ref="a3dc884d1fd5a29cbb7ef2c0fa7851717" args="(const cObject *obj, OppErrorCode errorcode, const char *fmt, va_list va)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void cException::init </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classcObject.html">cObject</a> *&nbsp;</td>
          <td class="paramname"> <em>obj</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">OppErrorCode&nbsp;</td>
          <td class="paramname"> <em>errorcode</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const char *&nbsp;</td>
          <td class="paramname"> <em>fmt</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">va_list&nbsp;</td>
          <td class="paramname"> <em>va</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td><td><code> [protected]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Helper function for constructors: assembles and stores the message text. </p>
<p>If the first arg is non-NULL, the message text will be prepended (if needed) with the object type and name, like this: "(cArray)array: ..." </p>

</div>
</div>
<a class="anchor" id="ae94e8963aaae31fc8609986128d38d52"></a><!-- doxytag: member="cException::isError" ref="ae94e8963aaae31fc8609986128d38d52" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual bool cException::isError </td>
          <td>(</td>
          <td class="paramname"></td>
          <td>&nbsp;)&nbsp;</td>
          <td> const<code> [inline, virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Whether the exception represents an error or a normal (non-error) terminating condition (e.g. </p>
<p>"Simulation completed"). </p>

<p>Reimplemented in <a class="el" href="classcTerminationException.html#a800ea3ac1413f70600cb9118eb7c1003">cTerminationException</a>, <a class="el" href="classcDeleteModuleException.html#a69946544e7468f833e5526a4478746a4">cDeleteModuleException</a>, and <a class="el" href="classcStackCleanupException.html#ab7728cfc9eb1e9d507f9ddbc7163f580">cStackCleanupException</a>.</p>

</div>
</div>
<a class="anchor" id="aec27fc122c18bc5432fb798188bb0af7"></a><!-- doxytag: member="cException::what" ref="aec27fc122c18bc5432fb798188bb0af7" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual const char* cException::what </td>
          <td>(</td>
          <td class="paramname"></td>
          <td>&nbsp;)&nbsp;</td>
          <td> const  throw ()<code> [inline, virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Returns the text of the error. </p>
<p>Redefined from std::exception. </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="cexception_8h_source.html">cexception.h</a></li>
</ul>
</div>
<hr class="footer"/><address style="text-align: right;"><small>Generated on Tue Dec 2 11:16:28 2014 for OMNeT++ Simulation Library by&nbsp;
<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.6.3 </small></address>
</body>
</html>
